# Descriptive analytics donor info

This notebook contains descriptive analytics about the donor info csv file. 

The combined data file contains the scores on the personality questionnaires and demographical data. 

Sum (combined scores from time point 4 until time point 7 on the BDRI questionnaire / vasovagal reactions)
sum2:

0. low VVR
1. high VVR (split on the mean value of the sum of BDRI scores)

In [1]:
# import 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load csv file 

In [2]:
donor_info_path = "/Users/dionnespaltman/Desktop/downloading/20221101_donor_info2.csv"

df = pd.read_csv(donor_info_path, index_col=0)
df = df.rename(columns={'sum': 'Sum'})
df = df.rename(columns={'binary': 'Binary'})

df_with_id = pd.read_csv(donor_info_path)

df.head()

Time_point          Path  Sum  Binary  Gender  Location  Condition
ID                                                                    
5            1  video5_1.MOV   12       0       2         0          1
5            1  video5_1.MOV   12       0       2         0          1
5            1  video5_1.MOV   12       0       2         0          1
5            1  video5_1.MOV   12       0       2         0          1
5            1  video5_1.MOV   12       0       2         0          1

In [18]:
# Assuming your DataFrame is named df
num_columns = df.shape[1]
print("Number of columns in the DataFrame:", num_columns)


Number of columns in the DataFrame: 7


In [3]:
display(df)

Time_point            Path  Sum  Binary  Gender  Location  Condition
ID                                                                       
5             1    video5_1.MOV   12       0       2         0          1
5             1    video5_1.MOV   12       0       2         0          1
5             1    video5_1.MOV   12       0       2         0          1
5             1    video5_1.MOV   12       0       2         0          1
5             1    video5_1.MOV   12       0       2         0          1
..          ...             ...  ...     ...     ...       ...        ...
291           2  video291_2.MOV   10       1       1         0          3
291           4  video291_4.MOV   12       0       1         0          3
291           5  video291_5.MOV    8       1       1         0          3
291           6  video291_6.MOV   10       1       1         0          3
291           7  video291_7.MOV    8       1       1         0          3

[15125 rows x 7 columns]

In [7]:
print(f"Number of categories in the ID column is {df_with_id.ID.nunique()}.")
print(f"Number of categories in the time point column is {df.Time_point.nunique()}.")
print(f"Number of categories in the path column is {df.Path.nunique()}.")
print(f"Number of categories in the sum column is {df.Sum.nunique()}.")
print(f"Number of categories in the binary column is {df.Binary.nunique()}.")
print(f"Number of categories in the gender column is {df.Gender.nunique()}.")
print(f"Number of categories in the location column is {df.Location.nunique()}.")
print(f"Number of categories in the condition column is {df.Condition.nunique()}.")

Number of categories in the ID column is 281.
Number of categories in the time point column is 7.
Number of categories in the path column is 2792.
Number of categories in the sum column is 21.
Number of categories in the binary column is 2.
Number of categories in the gender column is 2.
Number of categories in the location column is 3.
Number of categories in the condition column is 3.


# Experimental condition

1. control (experienced donors who did not have any vasovagal reactions previously)
2. experimental/sensitive (experienced donors who had vasovagal reaction at the previous donation)
3. first-time donors

In [4]:
condition_values = df['Condition'].unique()

print(condition_values)

[1 2 3]


# Unique IDs

We have 281 unique participants. 

In [8]:
# Assuming your DataFrame is named df
unique_ids = df.index.nunique()
print("Number of unique IDs:", unique_ids)


Number of unique IDs: 281


# Gender 

We have 119 in the 1st condition and 162 in the second condition. 

1. Male
2. Female      

In [11]:
# Assuming your DataFrame is named df
gender_counts = df.reset_index().drop_duplicates(subset='ID').groupby('Gender').size()
print(gender_counts)

Gender
1    119
2    162
dtype: int64


# Location - how can I get only 0, 1, 2 for location values instead of 0, 1, 2, 3? 

(Where the data was collected from)

0. Den Bosch
1. Leiden
2. Zwolle
3. Utrecht-Uithof    

In [15]:
location_values = df['Location'].unique()

print(location_values)

[0 1 2]


# Sum 

In [16]:
sum_values = df['Sum'].unique()

print(sum_values)

[12 10  9  8 11 14 40 18 16 15 13 20 19 17 21 25 26 23 22 24 30]


In [17]:
sum2_values = df['Sum2'].unique()

print(sum2_values)

KeyError: 'Sum2'